name = "ieee-creative-arena-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "ieee-creative-arena-db"
database_id = "49e8ec8b-ebb4-461e-a67d-e96183587c3a"  # Replace after creating D1 database

# Environment variables
[vars]
FRONTEND_URL = "https://op-team.shrooqhussien2.workers.dev/
